# Generated by Django 2.1.2 on 2018-10-15 03:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('M2', 'Menos de 2 años'), ('M2-5', '2 a 5 años'), ('M5-10', '5 a 10 años'), ('M10', 'mas de 10 años')], max_length=25)),
                ('valor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondIntensidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondExtension', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondDuracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondReversibilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondProbabilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('via', models.FloatField(blank=True, default=0)),
                ('duracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('GE', 'Generalizada (>75%)'), ('EX', 'Extensiva (35-74%)'), ('LO', 'Local (10-34%)'), ('PU', 'Puntual (<10%)')], max_length=25)),
                ('valor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradoIntensidad', models.CharField(choices=[('F', 'Fuerte'), ('M', 'Medio'), ('S', 'Suave')], max_length=25)),
                ('valoracionSA', models.CharField(choices=[('MA', 'Muy Alto'), ('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=25)),
                ('valor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relevancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efecto', models.CharField(max_length=50)),
                ('valoracion', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('DI', 'Directo'), ('IN', 'Indirecto')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reversibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('IR', 'Irreversible'), ('TR', 'Requiere Tratamiento'), ('MR', 'Medianamente Reversible'), ('RE', 'Reversible')], max_length=25)),
                ('valor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Extension'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='intensidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Intensidad'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='relevancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Relevancia'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='reversibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Reversibilidad'),
        ),
    ]
