# Generated by Django 2.2.dev20180914183443 on 2018-10-16 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20181016_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='clasificacion_extension',
            field=models.CharField(choices=[('GE', 'Generalizada (>75%)'), ('EX', 'Extensiva (35-74%)'), ('LO', 'Local (10-34%)'), ('PU', 'Puntual (<10%)')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='estudio',
            name='clasificacion_reversibilidad',
            field=models.CharField(choices=[('IR', 'Irreversible'), ('TR', 'Requiere Tratamiento'), ('MR', 'Medianamente Reversible'), ('RE', 'Reversible')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='estudio',
            name='criterio_duracion',
            field=models.CharField(choices=[('M2', 'Menos de 2 años'), ('M2-5', '2 a 5 años'), ('M5-10', '5 a 10 años'), ('M10', 'mas de 10 años')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='estudio',
            name='grado_perturbacion_intensidad',
            field=models.CharField(choices=[('F', 'Fuerte'), ('M', 'Medio'), ('S', 'Suave')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='estudio',
            name='importancia_estudio',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='estudio',
            name='valor_estudio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudio',
            name='valor_sociocultural_intensidad',
            field=models.CharField(choices=[('MA', 'Muy Alto'), ('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='extension',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='intensidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='probabilidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='reversibilidad',
            field=models.IntegerField(default=0),
        ),
    ]
