# Generated by Django 2.2.dev20180914183443 on 2018-10-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20181016_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='clasificacion_extension',
            field=models.CharField(choices=[('GE', 'Generalizada (>75%)'), ('EX', 'Extensiva (35-74%)'), ('LO', 'Local (10-34%)'), ('PU', 'Puntual (<10%)')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='clasificacion_reversibilidad',
            field=models.CharField(choices=[('IR', 'Irreversible'), ('TR', 'Requiere Tratamiento'), ('MR', 'Medianamente Reversible'), ('RE', 'Reversible')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='criterio_duracion',
            field=models.CharField(choices=[('M2', 'Menos de 2 años'), ('M2-5', '2 a 5 años'), ('M5-10', '5 a 10 años'), ('M10', 'mas de 10 años')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='grado_perturbacion_intensidad',
            field=models.CharField(choices=[('F', 'Fuerte'), ('M', 'Medio'), ('S', 'Suave')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='importancia_estudio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipo',
            field=models.CharField(choices=[('FS', 'Fisico'), ('BIO', 'Biologico'), ('SC', 'Socio-Cultural')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipo_relevancia',
            field=models.CharField(choices=[('DI', 'Directo'), ('IN', 'Indirecto')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='valor_sociocultural_intensidad',
            field=models.CharField(choices=[('MA', 'Muy Alto'), ('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='', max_length=50),
        ),
    ]
