# Generated by Django 2.2.dev20180914183443 on 2018-10-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_auto_20181018_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default='', error_messages={'unique': 'Ya existe un Estudio con el nombre colocado'}, max_length=100, unique=True),
        ),
    ]
