# Generated by Django 2.2.dev20180914183443 on 2018-10-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20181018_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 50 caracteres', 'unique': 'Ya existe un Estudio con el nombre colocado'}, max_length=50, unique=True),
        ),
    ]
