# Generated by Django 2.2.dev20180914183443 on 2018-10-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_auto_20181018_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres', 'unique': 'Ya existe un Estudio con el nombre colocado'}, max_length=40, unique=True),
        ),
    ]
