# Generated by Django 2.2.dev20180914183443 on 2018-10-29 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_auto_20181018_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('clasificacion', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('grado_perturbacion', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Reversibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
